### ISSUE TITLE
GitHub oAuth scope feels like an overkill

### ISSUE THREAD

**Issue by kaznovac** [rysolv/rysolv#15]
**Is your feature request related to a problem? Please describe.**
i'd like to sign up with a github account

**Describe the solution you'd like**
scope should be reduced to readonly status `read:user user:email` or to the public information only `(no scope)`
https://docs.github.com/en/free-pro-team@latest/developers/apps/scopes-for-oauth-apps#available-scopes

**Describe alternatives you've considered**
signing up with email and manual profile entry

**Additional context**
current scope can discourage people of integrating with github account (at least it discouraged me)

**Comment by tylermaran** [comment]
Hey @kaznovac. Agreed that this is overkill. And will be looking into a solution soon.

There is no reason for us to need read/write access to everything. Since honestly all we use Github for is verifying the email address. 

The Read/Write all is a weird choice by Github in their Oauth 2.0 structure. And it seems like the workaround is authenticating through a Github App instead: https://github.com/dear-github/dear-github/issues/113

Thanks for raising the issue. It's a big priority for us to fix.
