### ISSUE TITLE
UI improvements for repo cards

### ISSUE THREAD

**Issue by tylermaran** [rysolv/rysolv#86]
## Getting Started

To get started on this ticket, you'll want to have some data in the repos table. 

- Set up the db
  - with postgres installed, run `npm run seed` to seed the database
- Add a personal github token to the `.env` folder
  - https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token
- Sign in with github and go to 'new repo'. Add 3 or 4 repos
- Most of the changes should be in this folder: https://github.com/rysolv/rysolv/tree/master/app/components/Repos/Card

## Submitting a pull request
- Pull down all the latest changes and create a branch off of `dev`
- Name your branch First initial + Last initial / what-youre-doing
  - ex: `TM/update-repo-card`
- When you're done, open a pr against `dev` and ping someone to review
  - Link this issue to the pr with a comment (i.e. `closes #86`)
- A maintainer will review, make comments, and approve the pr
- When the PR is approved, we'll merge it into `dev` and delete the branch

## Proposed change

![repo-ui-update](https://user-images.githubusercontent.com/30934424/117585883-e1a95300-b0e2-11eb-9f89-c4a69553bf56.png)

## Claim this issue on Rysolv

https://rysolv.com/issues/detail/f81fd17d-4ef8-421d-90cd-da3281ddfe16

**Comment by ZeeshanZulfiqarAli** [comment]
@tylermaran would you prefer the logo to be in its original aspect ratio or stretched into a square?

![image](https://user-images.githubusercontent.com/32417658/118116543-da948480-b403-11eb-9e75-df79214a94e8.png)

**Comment by tylermaran** [comment]
I prefer it in the original aspect ratio. But I want the max height/width to be square.

Make sure that the image width in all the cards is the same, so it doesn't look staggered if there wide and narrow pictures. 

You may want to use the `object-fit`(https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit)
- `cover` would zoom in on the duck and crop the edges. 
- `contain` would show the whole image, but leave the white space

**Comment by ZeeshanZulfiqarAli** [comment]
![image](https://user-images.githubusercontent.com/32417658/118864409-65401c80-b8f9-11eb-8942-d4f5429bd61b.png)
So i have removed all the padding margin, added flex, and used gap to add spaces between the elements.

![image](https://user-images.githubusercontent.com/32417658/118864455-712bde80-b8f9-11eb-869e-e6668727ed95.png)
For the logo image, i have used **StyledImageLinkWrapper** which is placed in a styled div. This structure was already there, i merely modified the css in the div named **ImageContainer**.

As you mentioned in the issue about using _object-fit_, the problem is that in **RepoCard** component, i can't use it on the **ImageContainer** as it is a _div_, and i don't know if i should modify **StyledImageLinkWrapper** to support _object-fit_
Any thoughts?

**Comment by ZeeshanZulfiqarAli** [comment]
Putting it here after discussing with @tylermaran, for the sake of maintaining the comment history related to the issue:

I'll be trying to add _object-fit_ as a non-optional change first, and would check where else it is being used. This component is also being used in the user side, where we also had the aspect ratio issues. So it might be a double fix.

**Comment by tylermaran** [comment]
closed with #81

**Comment by tylermaran** [comment]
closed with #81
